name: tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: run tests
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: tests
        run: |
          ./support/test.sh ./about
